# Synchronize Issue Templates from here to several repositories.
# This lets us define issue templates in one place and then update them
# elsewhere as they are changed.
#
# Summary:
# - It uses a personal access token for @choldgraf with write permissions to 2i2c repositories
# - Upon commit to main, it will check for changes in the files defined in `sync.yml`
# - If a file is changed, it will make a PR to update that file in the target repositories
#
# ref: https://github.com/BetaHuhn/repo-file-sync-action

name: "Sync Issue Templates"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
          BRANCH_PREFIX: github
